// file: database/aws/rds-postgresql-standalone

// ---------------------------------------------------------------------------------------------------------------------
// Variables
// ---------------------------------------------------------------------------------------------------------------------

variable "environment" {
  description = "Name of the cloud environment (e.g. myenv)"
}

variable "application" {
  description = "Name of the application this belongs to (e.g. myapp)"
}

variable "service" {
  description = "Name of the service this resource belongs to (e.g. mysrv)"
  default     = ""
}

variable "allocated_storage" {
  description = "Data storage capacity in gigabytes (e.g. 100)"
  default     = 100
}

variable "database_name" {
  description = "Name of the database"
  default     = ""
}

variable "instance_size" {
  description = "The size of the database server"
  default     = "db.m1.small"
}

variable "iops" {
  description = "Number of provisioned IOPS to assign to the PostgreSQL server"
  default = 0
}

variable "master_username" {
  description = "Database users master username (e.g. admin)"
  default     = "admin"
}

variable "master_password" {
  description = "Database users master password (e.g. hunter2)"
}

variable "server_version" {}

variable "server_port" {
  description = "Port on which PostgreSQL server listens for connections"
  default     = 5432
}

variable "replicated" {
  default = true
}

variable "parameter_group_name" {
  description = "Database option group name"
  default     = ""
}

variable "pib_metadata" {
  description = "Metadata information consumed by Pib"
}

variable "subnet_group_name" {
  description = "Name of the subnet group name (autogenerated as $environment-$application if not provided)"
  default     = ""
}

variable "subnets" {
  description = "Database subnets"
}

// ---------------------------------------------------------------------------------------------------------------------
// Database Definition
// ---------------------------------------------------------------------------------------------------------------------

resource "random_id" "name" {
  byte_length = 16
}

resource "aws_db_subnet_group" "main" {
  name       = "${var.subnet_group_name == "" ? random_id.name.hex : var.subnet_group_name}"
  subnet_ids = ["${var.subnets}"]

  tags {
    "pib_metadata" = '{"app": "${var.application}", "service": "${var.service}", "resource_name": "${var.database_name}"}'
  }
}

resource "aws_db_instance" "main" {
  allocated_storage          = "${var.allocated_storage}"
  auto_minor_version_upgrade = true
  engine                     = "postgres"
  engine_version             = "${var.server_version}"
  instance_class             = "${var.instance_size}"
  name                       = "${var.database_name}"
  username                   = "${var.master_username}"
  password                   = "${var.master_password}"
  multi_az                   = "${var.replicated}"
  storage_type               = "${var.iops > 0 ? "io1" : "gp2" }"
  db_subnet_group_name       = "${aws_db_subnet_group.main.name}"
  publicly_accessible        = false
  parameter_group_name       = "${var.parameter_group_name != "" ? var.parameter_group_name : ""}"

  tags {
    "pib_metadata" = '{"app": "${var.application}", "service": "${var.service}", "resource_name": "${var.database_name}"}'
  }
}

// ---------------------------------------------------------------------------------------------------------------------
// Outputs
// ---------------------------------------------------------------------------------------------------------------------

output "address" { value = "${aws_db_instance.main.address}" }
output "arn"     { value = "${aws_db_instance.main.arn}" }
output "id"      { value = "${aws_db_instance.main.id}" }