// file: organization/aws/main.tf

variable "name" {
  description = "Name of the organization (all non-alphanumeric characters will be removed and the input will be lowercased)"
}

variable "kops_state_store_name" {
  description = "Name of the kops state store (autogenerated if not set)"
  default     = ""
}

variable "terraform_state_store_name" {
  description = "Name of the terraform state store (autogenerated if not set)"
  default     = ""
}

resource "aws_s3_bucket" "kops_state" {
  bucket = "${ var.kops_state_store_name != "" ? var.kops_state_store_name : replace(lower(var.name), "/[^a-zA-Z\\d]/", "")}-kops-state"

  versioning {
    enabled = true
  }
}

resource "aws_s3_bucket" "terraform_state" {
  bucket = "${ var.terraform_state_store_name != "" ? var.terraform_state_store_name : replace(lower(var.name), "/[^a-zA-Z\\d]/", "")}-terraform-state"

  versioning {
    enabled = true
  }
}

output "kops_state_store_bucket" { value = "${aws_s3_bucket.kops_state.bucket }" }
output "kops_state_store_arn"    { value = "${aws_s3_bucket.kops_state.arn}" }

output "terraform_state_store_bucket" { value = "${aws_s3_bucket.terraform_state.bucket }" }
output "terraform_state_store_arn"    { value = "${aws_s3_bucket.terraform_state.arn}" }

output "normalized_name" { value = "${replace(lower(var.name), "/[^a-zA-Z\\d]/", "")}" }